from PyQt5 import uic, QtCore
from PyQt5.QtWidgets import *
from lib.dojo_requests import SUPPORTED_BROWSERS
from lib.actions import save_grades, save_belts, save_usage
from setting import config, save_settings, SAVED_BELTS_KEY, SAVED_GRADES_KEY, SAVED_USAGES_KEY


class MainWindow(QMainWindow):

    def __init__(self, *args, **kwargs):
        """
        Uses the UI from PyQt5 designer
        :param args:
        :param kwargs:
        """
        super(MainWindow, self).__init__(*args, **kwargs)
        # Load the XML the was generated by the designer. This is
        # where the references to the widgets are created.
        uic.loadUi('gui.ui', self)

        self.site_ln.setText(config['site_name'])

        # Grades Save Path
        self.grades_save_path_ln.setText(config['file_config'].get(SAVED_GRADES_KEY, ''))
        self.grades_save_path_btn.clicked.connect(self.grades_save_as)

        # Belts Save Path
        self.belts_save_path_ln.setText(config['file_config'].get(SAVED_BELTS_KEY, ''))
        self.belts_save_path_btn.clicked.connect(self.belts_save_as)

        # Usages Save Path
        self.usages_save_path_ln.setText(config['file_config'].get(SAVED_USAGES_KEY, ''))
        self.usages_save_path_btn.clicked.connect(self.usages_save_as)

        # Browser Support Checkbox
        self.browser_cb.addItems(SUPPORTED_BROWSERS)
        self.browser_cb.setCurrentIndex(SUPPORTED_BROWSERS.index(config['browser']))
        self.browser_cb.currentIndexChanged.connect(self.browser_change)

        # Usage Excel Checkbox
        checked = True if config['file_config']['excel_format'] == 'true' else False
        self.excel_chbx.setChecked(checked)
        self.excel_chbx.stateChanged.connect(self.excel_box)

        # Download Grades
        self.download_grades_btn.clicked.connect(self.save_grades)

        # Download Belts
        self.belts_btn.clicked.connect(self.save_belts)

        # Download Usages
        self.usages_btn.clicked.connect(self.save_usage)

        self.show()

    def file_open(self):
        path, _ = QFileDialog.getOpenFileName(self, "Open file", "",
                                              "HTML documents (*.html);Text documents (*.txt);All files (*.*)")

        try:
            with open(path, 'rU') as f:
                text = f.read()

        except Exception as e:
            self.dialog_critical(str(e))

        else:
            # Qt will automatically try and guess the format as txt/html
            self.editor.setText(text)
            self.update_title()

    def file_saveas(self, name):
        path, _ = QFileDialog.getSaveFileName(self, "Save file", "",
                                              "CSV documents (*.csv)")

        if not path:
            # If dialog is cancelled, will return ''
            return

        try:
            with open(path, 'w') as f:
                f.write('tmp')

        except Exception as e:
            self.dialog_critical(str(e))

        else:
            config['file_config'][name] = path
            return path

    def grades_save_as(self):
        path = self.file_saveas(SAVED_GRADES_KEY)
        self.grades_save_path_ln.setText(path)

    def belts_save_as(self):
        path = self.file_saveas(SAVED_BELTS_KEY)
        self.belts_save_path_ln.setText(path)

    def usages_save_as(self):
        path = self.file_saveas(SAVED_USAGES_KEY)
        self.usages_save_path_ln.setText(path)

    def save_grades(self):
        file_name = config['file_config'].get(SAVED_GRADES_KEY, None)
        if not len(file_name) > 0:
            file_name = self.file_saveas(SAVED_GRADES_KEY)
            if not file_name:
                return
        search_term = self.search_ln.text()
        config['search_term'] = search_term
        try:
            self.status_ln.setText("Downloading Grades")
            self.status_ln.repaint()
            save_settings()
            save_grades(file_name, search_term)
            self.status_ln.setText("Done")
        except EnvironmentError:
            self.status_ln.setText("Error: Browser not logged in")

    def save_belts(self):
        file_name = config['file_config'].get(SAVED_BELTS_KEY, None)
        if not len(file_name) > 0:
            file_name = self.file_saveas(SAVED_BELTS_KEY)
            if not file_name:
                return
        site_name = self.site_ln.text()
        if not site_name:
            self.status_ln.setText("Error: Need site name to get belt data")
        try:
            config['site_name'] = site_name
            self.status_ln.setText("Downloading Belts")
            self.status_ln.repaint()
            save_belts(file_name, site_name)
            self.status_ln.setText("Done")
        except EnvironmentError:
            self.status_ln.setText("Error: Browser not logged in")

    def save_usage(self):
        file_name = config['file_config'].get(SAVED_USAGES_KEY, None)
        if not len(file_name) > 0:
            file_name = self.file_saveas(SAVED_USAGES_KEY)
            if not file_name:
                return
        site_name = self.site_ln.text()
        if 'ex:' in site_name or not site_name:
            self.status_ln.setText("Error: Need site name to get usage data")
            return
        try:
            config['site_name'] = site_name
            self.status_ln.setText("Downloading Usage")
            self.status_ln.repaint()
            excel = True if config['file_config'].get('excel_format') == 'true' else False
            save_usage(file_name, site_name, excel_fmt=excel)
            self.status_ln.setText("Done")
        except EnvironmentError:
            self.status_ln.setText("Error: Browser not logged in")

    def browser_change(self, i):
        config['browser'] = self.browser_cb.itemText(i)
        return self.browser_cb.itemText(i)

    def keyPressEvent(self, event):
        """Close application from escape key.

        results in QMessageBox dialog from closeEvent, good but how/why?
        """
        if event.key() == QtCore.Qt.Key_Escape:
            self.close()

    def closeEvent(self, event):
        """Generate 'question' dialog on clicking 'X' button in title bar.

        Reimplement the closeEvent() event handler to include a 'Question'
        dialog with options on how to proceed - Save, Close, Cancel buttons
        """
        reply = QMessageBox.question(
            self, "Message",
            "Would you like to save the current configuration before quitting?",
            QMessageBox.Save | QMessageBox.Close | QMessageBox.Cancel,
            QMessageBox.Save)

        if reply == QMessageBox.Close:
            event.accept()
        elif reply == QMessageBox.Save:
            save_settings()
            event.accept()
        else:
            event.ignore()

    def excel_box(self, state):
        if state == QtCore.Qt.Checked:
            config['file_config']['overwrite'] = 'true'
        else:
            config['file_config']['overwrite'] = 'false'
